# Generated by Django 5.2.12 on 2026-03-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('manicure', 'Маникюр и педикюр'), ('hair', 'Волосы'), ('skin', 'Уход за кожей'), ('brows', 'Брови и ресницы'), ('makeup', 'Макияж'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
