# Generated by Django 5.2.12 on 2026-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото услуги'),
        ),
    ]
